wallpaper {
  monitor = DP-1
  path = ~/Images/Wallpapers/vertical_simple_yellow.png
  fit_mode = cover
}

wallpaper {
  monitor = DP-2
  path = ~/Images/Wallpapers/horizontal_bar_text_yellow.png
  fit_mode = cover
}
