theme {
  color_scheme = "/home/lmoura/Ricing/Orchis-kde/color-schemes/OrchisDark.colors"
  icon_theme = "Tela circle yellow dark"
  style = "kvantum-dark"
  font_fixed = "CaskaydiaCove Nerd Font Regular"
  font_fixed_size = 16
  font = "Lato Regular"
  font_size = 16
}
